export enum ActionTypes {
    SET_BOOKS_LOADING = 'SET_BOOKS_LOADING',
    SEARCH_BOOKS = 'SEARCH_BOOKS',
    SET_BOOKS = 'SET_BOOKS',
    SET_ERROR_BOOKS_SEARCHING = 'SET_ERROR_BOOKS_SEARCHING',
    SET_DOWNLOADING_DATE = 'SET_DOWNLOADING_DATE',
}

export default ActionTypes
